namespace Grand.Plugin.Widgets.SwiperSlider
{
    /// <summary>
    /// Represents jQuery Animation types
    /// </summary>
    public enum AnimationType : int
    {

        bounce = 1,
        flash = 2,
        pulse = 3,
        rubberBand = 4,
        shake = 5,
        headShake = 6,
        swing = 7,
        tada = 8,
        wobble = 9,
        jello = 10,
        bounceIn = 11,
        bounceInDown = 12,
        bounceInLeft = 13,
        bounceInRight = 14,
        bounceInUp = 15,
        bounceOut = 16,
        bounceOutDown = 17,
        bounceOutLeft = 18,
        bounceOutRight = 19,
        bounceOutUp = 20,
        fadeIn = 21,
        fadeInDown = 22,
        fadeInDownBig = 23,
        fadeInLeft = 24,
        fadeInLeftBig = 25,
        fadeInRight = 26,
        fadeInRightBig = 27,
        fadeInUp = 28,
        fadeInUpBig = 29,
        fadeOut = 30,
        fadeOutDown = 31,
        fadeOutDownBig = 32,
        fadeOutLeft = 33,
        fadeOutLeftBig = 34,
        fadeOutRight = 35,
        fadeOutRightBig = 36,
        fadeOutUp = 37,
        fadeOutUpBig = 38,
        flipInX = 39,
        flipInY = 40,
        flipOutX = 41,
        flipOutY = 42,
        lightSpeedIn = 43,
        lightSpeedOut = 44,
        rotateIn = 45,
        rotateInDownLeft = 46,
        rotateInDownRight = 47,
        rotateInUpLeft = 48,
        rotateInUpRight = 49,
        rotateOut = 50,
        rotateOutDownLeft = 51,
        rotateOutDownRight = 52,
        rotateOutUpLeft = 53,
        rotateOutUpRight = 54,
        hinge = 55,
        jackInTheBox = 56,
        rollIn = 57,
        rollOut = 58,
        zoomIn = 59,
        zoomInDown = 60,
        zoomInLeft = 61,
        zoomInRight = 62,
        zoomInUp = 63,
        zoomOut = 64,
        zoomOutDown = 65,
        zoomOutLeft = 66,
        zoomOutRight = 67,
        zoomOutUp = 68,
        slideInDown = 69,
        slideInLeft = 70,
        slideInRight = 71,
        slideInUp = 72,
        slideOutDown = 73,
        slideOutLeft = 74,
        slideOutRight = 75,
        slideOutUp = 76,
        heartBeat = 77,
    }
}
